/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.util.concurrent.ThreadFactory;
import com.google.zxing.common.HybridBinarizer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Joshua Formento
 */
public class QRCodeScan extends javax.swing.JFrame implements Runnable,ThreadFactory {

    private WebcamPanel panel = null;
    private Webcam webcam = null;
    private Executor executor = Executors.newSingleThreadExecutor(this);
    
        public static class Function{
        
        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement ps = null;
        final String DB_URL = "jdbc:mysql://localhost/finalprojectdb?serverTimezone=UTC";
        final String USERNAME = "root";
        final String PASSWORD = "";

        public ResultSet find(String s) throws SQLException {
            try {
                conn = DriverManager.getConnection(DB_URL, USERNAME, PASSWORD);
                ps = conn.prepareStatement("select * from equipmentinventory where id = ?");
                ps.setString(1,s);
                rs = ps.executeQuery();
            } catch (Exception e){
                e.printStackTrace();
            }
            return rs;
        }
        }

    /**
     * Creates new form QRCodeScan
     */
    public QRCodeScan() {
        initComponents();
        initWebcam();
        setTitle("Laboratory Equipment Inventory: Borrow");
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }
        Connection con;
        PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        equip_name = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        borrower_name = new javax.swing.JTextField();
        inuse = new javax.swing.JTextField();
        borrowBtn = new javax.swing.JButton();
        scanBtn = new javax.swing.JButton();
        result_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Couture", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Laboratory Equipment Inventory ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, 38));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Quarion", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setFont(new java.awt.Font("Quarion", 1, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(0, 0, 0));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, -1, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(180, 180));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 200, 190));

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("equipment name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, 30));

        jLabel3.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("in use/not:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, 30));

        jLabel4.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("borrower name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, 30));

        jLabel5.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("status:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, 30));

        jLabel6.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 30));

        equip_name.setEditable(false);
        equip_name.setFont(new java.awt.Font("Proxima Nova Alt Lt", 0, 14)); // NOI18N
        equip_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equip_nameActionPerformed(evt);
            }
        });
        getContentPane().add(equip_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 250, -1));

        status.setEditable(false);
        status.setFont(new java.awt.Font("Proxima Nova Alt Lt", 0, 14)); // NOI18N
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 250, -1));

        borrower_name.setFont(new java.awt.Font("Proxima Nova Alt Lt", 0, 14)); // NOI18N
        getContentPane().add(borrower_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 250, -1));

        inuse.setFont(new java.awt.Font("Proxima Nova Alt Lt", 0, 14)); // NOI18N
        getContentPane().add(inuse, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 250, -1));

        borrowBtn.setBackground(new java.awt.Color(255, 255, 255));
        borrowBtn.setFont(new java.awt.Font("Quarion", 1, 14)); // NOI18N
        borrowBtn.setForeground(new java.awt.Color(0, 0, 0));
        borrowBtn.setText("Borrow");
        borrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBtnActionPerformed(evt);
            }
        });
        getContentPane().add(borrowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        scanBtn.setBackground(new java.awt.Color(255, 255, 255));
        scanBtn.setFont(new java.awt.Font("Quarion", 1, 14)); // NOI18N
        scanBtn.setForeground(new java.awt.Color(0, 0, 0));
        scanBtn.setText("Scan");
        scanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanBtnActionPerformed(evt);
            }
        });
        getContentPane().add(scanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        result_field.setEditable(false);
        result_field.setFont(new java.awt.Font("Proxima Nova Alt Lt", 0, 14)); // NOI18N
        result_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(result_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 250, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/images/Artboard 1.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        StudentLogin login = new StudentLogin();
        login.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void equip_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equip_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equip_nameActionPerformed

    private void borrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBtnActionPerformed
        try {
            String newName = borrower_name.getText();
            String use = inuse.getText();

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(QRCodeScan.class.getName()).log(Level.SEVERE, null, ex);
            }
            con = DriverManager.getConnection("jdbc:mysql://localhost/finalprojectdb","root","");
            java.sql.Statement stm = con.createStatement();
            String sql = "INSERT INTO equipmentinventory (BORROWER, INUSE) VALUES ('"+newName+"','"+use+"')";
            stm.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "You can now borrow.");
            new QRCodeScan().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(QRCodeScan.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_borrowBtnActionPerformed

    private void scanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanBtnActionPerformed
        QRCodeScan cam = new QRCodeScan();
        cam.setVisible(true);
    }//GEN-LAST:event_scanBtnActionPerformed

    private void result_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_result_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QRCodeScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QRCodeScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QRCodeScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QRCodeScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QRCodeScan().setVisible(true);
        });
    }
private void initWebcam(){
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 320, 230));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 200, 190));
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("QR Code Scanner");          
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0);
        webcam.setViewSize(size);
        
        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        jPanel2.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960,540,445,250));
        executor.execute(this);
        
    }
    
    @Override
    public void run(){
        do{
            try{
                Thread.sleep(100);
            }catch (InterruptedException ex){
                Logger.getLogger(QRCodeScan.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Result result = null;
            BufferedImage image = null;
            
            if(webcam.isOpen()){
                if((image= webcam.getImage())== null){
                   continue; 
                }
            }
            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
            
            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (NotFoundException ex) {
                java.util.logging.Logger.getLogger(QRCodeScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            
            if(result != null){
                result_field.setText(result.getText());
            }
            Function f = new Function();
            ResultSet rs = null;
            String en = "EQUIPMENTNAME";
            String br = "BORROWER";
            String stat = "STATUS";
            String iu = "INUSE";
            String input = result_field.getText();
            
            
            try{
                rs = f.find(input);

            if (rs.next()){
                equip_name.setText(rs.getString(en));
                borrower_name.setText(rs.getString(br));
                status.setText(rs.getString(stat));
                inuse.setText(rs.getString(iu));
            } else {
                JOptionPane.showMessageDialog(null, "No data found.");
                break;
            }
        } catch (Exception ex){
    JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        }while(true);
        
    }
    public Thread newThread(Runnable r){
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton borrowBtn;
    private javax.swing.JTextField borrower_name;
    private javax.swing.JTextField equip_name;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField inuse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField result_field;
    private javax.swing.JButton scanBtn;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
