package main.java;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Joshua Formento
 */

public class StudentLogin extends javax.swing.JFrame {

    /**
     * Creates new form StudentLogin
     */
    public StudentLogin() {
        initComponents();
        setTitle("Student Login");
        setLocationRelativeTo(null);
        setVisible(true); 
        Connect();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public boolean verifyField() {
        String user = srcodeTF.getText();

        if (user.trim().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Some fields are empty!", "Make sure they are not empty!",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }
    
public boolean checkUsername(String srcode) {
        PreparedStatement ps;
        ResultSet rs;
        boolean existingUser = false;

        String query = "SELECT * FROM student_info WHERE SRCODE = ?";
        try {
            ps = Myconnection.getConnection().prepareStatement(query);
            ps.setString(1, srcode);
            rs = ps.executeQuery();

            if (rs.next()) {
                existingUser = true;
                JOptionPane.showMessageDialog(null, "This SR-Code already exists", "Use another SR-Code.",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Myconnection.class.getName()).log(Level.SEVERE, null, ex);
        }
        return existingUser;
    }

public void Connect(){
    
    
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/finalprojectdb","root","");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        srcodeTF = new javax.swing.JTextField();
        signBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passTF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Couture", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Laboratory Equipment BORROWING SYSTEM ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 38));

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("sr-code:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, 30));

        jLabel4.setFont(new java.awt.Font("BookmanOldStyleProCyrW04-Rg", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("BATANGAS STATE UNIVERSITY");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 50));

        jLabel5.setFont(new java.awt.Font("BookmanOldStyleProCyrW04-Rg", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("The National Engineering University");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 60, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/images/icons8_key_30px_1.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, 40));

        jLabel10.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText(" Password:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, 30));

        passwordTF.setFont(new java.awt.Font("Proxima Nova Rg", 0, 14)); // NOI18N
        passwordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTFActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 220, -1));

        srcodeTF.setFont(new java.awt.Font("Proxima Nova Rg", 0, 14)); // NOI18N
        srcodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcodeTFActionPerformed(evt);
            }
        });
        getContentPane().add(srcodeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 220, -1));

        signBtn.setBackground(new java.awt.Color(255, 255, 255));
        signBtn.setFont(new java.awt.Font("Quarion", 1, 14)); // NOI18N
        signBtn.setForeground(new java.awt.Color(0, 0, 0));
        signBtn.setText("Sign Up");
        signBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signBtnActionPerformed(evt);
            }
        });
        getContentPane().add(signBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        clearBtn.setBackground(new java.awt.Color(255, 255, 255));
        clearBtn.setFont(new java.awt.Font("Quarion", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(0, 0, 0));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setFont(new java.awt.Font("Quarion", 1, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(0, 0, 0));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        loginBtn.setBackground(new java.awt.Color(255, 255, 255));
        loginBtn.setFont(new java.awt.Font("Quarion", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/images/icons8_contacts_32px.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 30, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/images/Artboard 1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/images/icons8_key_30px_1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, 40));

        jLabel7.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Password:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 90, 30));

        passTF.setFont(new java.awt.Font("Proxima Nova Rg", 0, 14)); // NOI18N
        getContentPane().add(passTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srcodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcodeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcodeTFActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        new Welcome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        srcodeTF.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void signBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signBtnActionPerformed
        String sr = srcodeTF.getText();
    String password = new String(passwordTF.getPassword());

    if (verifyField()) {
        if (!checkUsername(sr)) {
            PreparedStatement ps;
            String register = "INSERT INTO student_info (SRCODE, PASSWORD) VALUES (?, ?)";

            try {
                ps = con.prepareStatement(register);
                ps.setString(1, sr);
                ps.setString(2, password);

                if (ps.executeUpdate() != 0) {
                    JOptionPane.showMessageDialog(null, "Account has been added");
                }

            } catch (SQLException ex) {
                throw new RuntimeException(ex);
            }
            srcodeTF.setText("");
            passwordTF.setText(""); // Clear password field after sign-up
        }
    }
    }//GEN-LAST:event_signBtnActionPerformed
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String sr = srcodeTF.getText();
    String password = new String(passwordTF.getPassword());

    if (verifyField()) {
        srcode = getAuthenticatedUser(sr, password);

        if (srcode != null) {
            ReadQrcode scan = new ReadQrcode(sr);
            scan.setVisible(true);
            this.setVisible(false);// Successful login logic
        } else {
            JOptionPane.showMessageDialog(StudentLogin.this, "SR-Code or password is invalid.", "Try again", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void passwordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogin().setVisible(true);
            }
        });
    }
    public static loginCredentials srcode;

    private loginCredentials getAuthenticatedUser(String sr, String password) {
        loginCredentials user = null;

    final String DB_URL = "jdbc:mysql://localhost/finalprojectdb?serverTimezone=Asia/Manila";
    final String USERNAME = "root";
    final String PASSWORD = "";

    try {
        Connection conn = DriverManager.getConnection(DB_URL, USERNAME, PASSWORD);

        String sql = "SELECT * FROM student_info WHERE SRCODE=? AND PASSWORD=?";
        PreparedStatement preparedStatement = conn.prepareStatement(sql);
        preparedStatement.setString(1, sr);
        preparedStatement.setString(2, password);

        ResultSet resultSet = preparedStatement.executeQuery();

        if (resultSet.next()) {
            user = new loginCredentials();
            user.sr = resultSet.getString("SRCODE");
        }

        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }

    return user;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton signBtn;
    private javax.swing.JTextField srcodeTF;
    // End of variables declaration//GEN-END:variables
}
